const main=document.querySelector('#main');document.querySelector('#year').parentElement.textContent='© 2026 Proyecto Bosco. Todos los derechos reservados.';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let config,content,session,sessionError='';
async function api(path,body){const r=await fetch(path,{credentials:'same-origin',...(body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{})});const j=await r.json();if(!r.ok){const e=new Error(j.error||'No se pudo completar la solicitud.');e.retryAfter=j.retryAfter;throw e;}return j;}
const dt=new Intl.DateTimeFormat('es-MX',{weekday:'long',day:'numeric',month:'long',hour:'2-digit',minute:'2-digit',timeZone:'America/Mexico_City'});
function bookingInfo(){if(!session.booking.start)return `<div class="booking-info"><strong>Horario</strong><p>${session.booking.mode==='demo'?'Este horario local no es una reserva real.':'Consulta la confirmación de tu calendario para ver los detalles.'}</p></div>`;return `<div class="booking-info"><strong>Tu horario</strong><p>${esc(dt.format(new Date(session.booking.start)))}</p></div>`;}
function section(label,title,inner){return `<section class="section"><p class="eyebrow">${esc(label)}</p><h2>${esc(title)}</h2>${inner}</section>`;}
function video(src,vsl=false,poster=''){return `<div class="media" data-video><video ${vsl?'':'controls'} playsinline preload="none" ${poster?`poster="${esc(poster)}"`:''} aria-label="${vsl?'Presentación del proyecto':'Testimonio de inversionista'}"><source src="${esc(src)}" type="video/mp4"></video>${vsl?'<div class="media-controls"><label class="media-seek"><span>Avance del video</span><input type="range" min="0" max="0" step="0.1" value="0" data-seek aria-label="Avanzar o retroceder video"></label><button type="button" data-play>Reproducir</button><button type="button" data-mute aria-pressed="false">Silenciar</button><button type="button" data-full>Pantalla completa</button></div>':''}<p class="status" hidden></p></div>`;}
function mountMedia(){const compactCases=[...document.querySelectorAll('.case')].filter(article=>['Rogel','Ana Karen'].includes(article.querySelector('h3')?.textContent.trim()));if(compactCases.length===2){const group=document.createElement('div');group.className='compact-cases';compactCases[0].before(group);for(const article of compactCases){const title=article.querySelector('h3'),media=article.querySelector('.case-layout .media');article.classList.add('compact-case');article.replaceChildren(title,media);group.append(article);}}document.querySelectorAll('[data-video]').forEach(box=>{const v=box.querySelector('video');const play=box.querySelector('[data-play]'),mute=box.querySelector('[data-mute]'),seek=box.querySelector('[data-seek]');const fail=()=>{box.innerHTML='<div class="media-placeholder"><strong>Video no disponible</strong><span>Intenta nuevamente más tarde.</span></div>';};v.addEventListener('error',fail);v.querySelector('source').addEventListener('error',fail);
if(seek){const updateSeek=()=>{if(Number.isFinite(v.duration)){seek.max=String(v.duration);if(document.activeElement!==seek)seek.value=String(v.currentTime);}};v.addEventListener('loadedmetadata',updateSeek);v.addEventListener('durationchange',updateSeek);v.addEventListener('timeupdate',updateSeek);seek.oninput=()=>{if(Number.isFinite(v.duration))v.currentTime=Number(seek.value);};}
if(play){play.onclick=async()=>{try{if(v.paused){await v.play();}else v.pause();}catch{box.querySelector('.status').hidden=false;box.querySelector('.status').textContent='No se pudo reproducir el video. Intenta nuevamente.';}};v.addEventListener('play',()=>play.textContent='Pausar');v.addEventListener('pause',()=>play.textContent='Reproducir');mute.onclick=()=>{v.muted=!v.muted;mute.textContent=v.muted?'Activar sonido':'Silenciar';mute.setAttribute('aria-pressed',String(v.muted));};box.querySelector('[data-full]').onclick=async()=>{try{if(box.requestFullscreen)await box.requestFullscreen();else if(v.webkitEnterFullscreen)v.webkitEnterFullscreen();}catch{}};}
});document.querySelectorAll('img').forEach(i=>i.addEventListener('error',()=>{i.hidden=true;const p=document.createElement('p');p.className='notice';p.textContent='Imagen no disponible.';i.after(p);}));}
async function landing(){const h=esc(content.hero.title).replace('&lt;em&gt;','<em>').replace('&lt;/em&gt;','</em>');main.innerHTML=`<section class="hero"><p class="eyebrow">BOSCO · MÉRIDA, YUCATÁN</p><h1>${h}</h1><p>${esc(content.hero.subtitle)}</p><div id="vsl-slot"></div></section><p class="convert"><a class="continue-link" href="/registro">Continuar al registro <span aria-hidden="true">→</span></a></p>`+
section('CASOS REALES','Resultados de mis clientes',content.cases.map(c=>`<article class="case"><div class="case-layout"><div class="case-copy"><h3>${esc(c.name)}</h3>${c.quote?`<blockquote>“${esc(c.quote)}”</blockquote>`:''}${c.summary?`<p>${esc(c.summary)}</p>`:''}${c.metric?`<p class="metric">${esc(c.metric)}</p>`:''}</div>${c.video?video(c.video,false,c.poster):`<img class="case-photo" src="${esc(c.image)}" alt="${esc(c.name)} con Marisol" loading="lazy">`}</div></article>`).join('')+(content.pendingCase?.enabled?`<article class="case"><h3>${esc(content.pendingCase.name)} · inversionista satisfecho</h3><img class="case-photo" src="${esc(content.pendingCase.image)}" alt="${esc(content.pendingCase.name)}" loading="lazy"></article>`:''))+
section('POR QUÉ ESTE PROYECTO ES SEGURO','4 razones por las que tu inversión está protegida',trustBlocks())+
section('EL PROYECTO','Todo lo que obtienes al invertir en este proyecto',`<p>Un departamento que trabaja por ti — con acompañamiento real de inicio a fin.</p>${list(content.offer,'offer-list')}<div class="media"><img src="${esc(content.assets.project)}" alt="Avance de construcción del proyecto BOSCO" loading="lazy" width="1200" height="800"></div><div class="location-block"><p class="eyebrow">DÓNDE ESTÁ TU INVERSIÓN</p><h3>${esc(content.location.title)}</h3><p>${esc(content.location.description)}</p><div class="news">${content.news.map(n=>`<article><img class="news-image" src="${esc(n.image)}" alt="${esc(n.imageAlt)}" loading="lazy" decoding="async"><strong>${esc(n.source)}</strong><p>${esc(n.title)}</p></article>`).join('')}</div><p class="fine">${esc(content.location.delivery)} · ${esc(content.location.developer)}</p></div>`)+
section('MÁS INVERSIONISTAS CONTENTOS',content.investorsTitle,`<div class="investors">${content.assets.investors.map((src,i)=>`<img src="${esc(src)}" loading="lazy" decoding="async" width="600" height="600" alt="Inversionistas del proyecto, fotografía ${i+1}">`).join('')}</div>`);
try{const r=await fetch(content.assets.vsl,{method:'HEAD'});document.querySelector('#vsl-slot').innerHTML=r.ok?video(content.assets.vsl,true):'<div class="media media-placeholder"><strong>Presentación del proyecto</strong><span>El video estará disponible próximamente.</span></div>';}catch{document.querySelector('#vsl-slot').innerHTML='<p>El video no está disponible en este momento.</p>'; }mountMedia();mountMotion();}
function trustBlocks(){return `<div class="trust-blocks">${content.trust.map(([title,text],i)=>`<article class="trust-block"><div class="trust-copy"><span class="number">${String(i+1).padStart(2,'0')}</span><h3>${esc(title)}</h3><p>${emphasis(text)}</p></div>${trustVisual(content.trustMedia[i])}</article>`).join('')}</div>`;}
function emphasis(text){let safe=esc(text);for(const phrase of ['PROFECO','15 años de experiencia','licencias de construcción','tu inversión está protegida','invertí en él','propio dinero'])safe=safe.replace(phrase,`<strong>${phrase}</strong>`);return safe;}
function trustVisual(m){if(m.kind==='projects')return `<figure class="trust-visual"><div class="project-pair">${m.images.map(src=>`<img src="${esc(src)}" loading="lazy" alt="Proyecto de CONSUR">`).join('')}</div><figcaption>${esc(m.label)}</figcaption></figure>`;if(m.kind==='photo')return `<figure class="trust-visual"><img src="${esc(m.image)}" loading="lazy" alt="Marisol en la obra del proyecto BOSCO"><figcaption>${esc(m.label)}</figcaption></figure>`;return `<figure class="trust-visual document-illustration"><div class="paper-stack ${m.kind==='permits'?'four-papers':''}" aria-hidden="true">${Array.from({length:m.kind==='permits'?4:2},()=>'<div class="paper"><span></span><i></i><i></i><i></i><i></i><i></i><b></b></div>').join('')}</div><figcaption>${esc(m.label)}</figcaption></figure>`;}
function mountMotion(){if(matchMedia('(prefers-reduced-motion: reduce)').matches||!('IntersectionObserver' in window))return;const observer=new IntersectionObserver(entries=>{entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('is-visible');observer.unobserve(e.target);}});},{threshold:.08});document.querySelectorAll('.trust-block,.case,.item,.news article').forEach(e=>{e.classList.add('reveal');observer.observe(e);});}
function list(items,variant=''){return `<div class="list ${esc(variant)}">${items.map(([title,text],i)=>`<article class="item"><span class="number">${String(i+1).padStart(2,'0')}</span><div><h3>${esc(title)}</h3><p>${esc(text)}</p></div></article>`).join('')}</div>`;}
const fields=[['experience','¿Ya has invertido en bienes raíces antes?',[['experienced','Sí, ya tengo experiencia'],['first-time','No, es mi primera vez']]],['goal','¿Qué quieres lograr con esta inversión?',[['income','Generar ingresos pasivos sin depender de mi trabajo'],['family','Construir patrimonio para mi familia'],['diversify','Diversificar lo que ya tengo invertido'],['bank','Hacer crecer mi dinero que está parado en el banco']]],['timeline','¿En cuánto tiempo quieres invertir?',[['30days','En los próximos 30 días'],['2-3months','En 2 o 3 meses'],['evaluating','Todavía lo estoy evaluando']]],['capital','¿Con cuánto capital cuentas hoy para invertir?',[['under-250k','Menos de $250,000 MXN'],['250-500k','$250,000 – $500,000 MXN'],['over-500k','Más de $500,000 MXN']]],['monthly','¿Cuánto puedes destinar mensualmente?',[['under-5k','Menos de $5,000'],['5-10k','$5,000 – $10,000'],['over-10k','Más de $10,000']]],['decision','¿La decisión de invertir depende únicamente de ti?',[['solo','Sí, decido yo solo'],['partner','No, lo decido con mi pareja o esposo(a)'],['family','No, lo decido con un socio o familiar']]]];
function qualification(preview=false){main.innerHTML=`<a class="back" href="/registro">← Volver a la agenda</a><ol class="flow-steps" aria-label="Pasos de registro"><li>1. Agenda</li><li aria-current="step">2. Datos y preguntas</li><li>3. Resultado</li></ol>${preview?'<p class="notice preview-notice">Vista previa local explícita: no se crean reservas ni se guardan o envían respuestas.</p>':bookingInfo()}<header class="qualification-header"><h1><span>Cuéntanos un poco</span><em>sobre ti</em></h1><p>Solo toma 1 minuto. Nos ayuda a preparar tu sesión para que sea 100% efectiva para ti.</p></header>${!preview&&session.booking.mode==='demo'?'<p class="notice">Estás probando el recorrido local. Este horario no crea una reunión real ni envía correos.</p>':''}<form class="panel form-grid" id="qualification"><label class="full">Nombre completo<input name="name" autocomplete="name" maxlength="100" required ${!preview?`value="${esc(session.booking.name||'')}"`:''}></label><label>WhatsApp<input name="whatsapp" type="tel" autocomplete="tel" maxlength="25" placeholder="+52…" required></label><label>Email<input name="email" type="email" autocomplete="email" maxlength="254" required ${!preview?`value="${esc(session.booking.email||'')}"`:''}></label>${fields.map(([name,label,options])=>`<label class="full">${esc(label)}<select name="${name}" required><option value="">Selecciona una opción</option>${options.map(([v,l])=>`<option value="${v}">${esc(l)}</option>`).join('')}</select></label>`).join('')}<p class="privacy-link full"><a href="/privacidad">Privacy Policy</a></p><button class="button full" type="submit">${preview?'Probar validación local':'Enviar mis respuestas'}</button><p class="status full" role="status" aria-live="polite"></p></form>`;
if(preview){const form=document.querySelector('#qualification');form.onsubmit=e=>{e.preventDefault();form.querySelector('.status').textContent='Vista previa: el formulario se validó en tu navegador. No se guardó ni envió ninguna respuesta.';};return;}
bindForm(document.querySelector('#qualification'),'/api/qualification',j=>location.assign(j.qualified?'/gracias':'/no-apto'));}
function bindForm(form,url,success){let busy=false;form.onsubmit=async e=>{e.preventDefault();if(busy)return;busy=true;const button=form.querySelector('button[type=submit]'),status=form.querySelector('.status');button.disabled=true;status.textContent='Enviando…';try{const values=Object.fromEntries(new FormData(form));success(await api(url,values));}catch(error){status.textContent=error.message;if(error.retryAfter){let left=error.retryAfter;const timer=setInterval(()=>{left--;status.textContent=`Puedes volver a enviar en ${left} segundos.`;if(left<=0){clearInterval(timer);status.textContent='Ya puedes volver a enviar.';button.disabled=false;busy=false;}},1000);return;}button.disabled=false;busy=false;}};}
async function registration(){
if(!config.storageReady){main.innerHTML='<div class="panel"><h1>No se puede guardar tu reserva todavía</h1><p>El almacenamiento persistente no está configurado. No se guardará ninguna información.</p></div>';return;}
if(sessionError){main.innerHTML=`<div class="panel"><h1>No pudimos consultar tu sesión</h1><p>${esc(sessionError)}</p><a href="/registro">Volver a intentar</a></div>`;return;}
if(session.qualification)return location.replace(session.qualification.qualified?'/gracias':'/no-apto');
if(session.booking)return qualification();
main.innerHTML=`<a class="back" href="/">← Volver al proyecto</a><ol class="flow-steps" aria-label="Pasos de registro"><li aria-current="step">1. Agenda</li><li>2. Datos y preguntas</li><li>3. Resultado</li></ol><p class="eyebrow">SESIÓN CON MARISOL</p><h1>Elige tu horario</h1><p>Después de confirmar tu reserva, completarás tus datos y preguntas en esta misma página.</p><div id="calendar" class="panel"><p role="status">Cargando agenda…</p></div><div class="panel qualification-preview"><h2>Después de agendar</h2><p>Completarás tus datos y preguntas para preparar tu sesión.</p><div class="preview-fields" aria-hidden="true"><span>Nombre y contacto</span><span>Objetivo y plazo</span><span>Capital y mensualidad</span></div></div>`;
const box=document.querySelector('#calendar');
if(config.mode==='ghl-embed'){
box.innerHTML=`<iframe class="calendar-embed" src="${esc(config.ghlCalendarUrl)}" title="Calendario de GoHighLevel" loading="lazy" allow="camera; microphone; fullscreen; payment"></iframe><p class="notice">Calendario de GoHighLevel configurado. Las preguntas se habilitarán cuando el backend reciba y verifique la confirmación de la reserva; el calendario aún no está conectado a esa confirmación.</p><a href="${esc(config.ghlCalendarUrl)}" target="_blank" rel="noopener noreferrer">Abrir calendario de GoHighLevel en otra pestaña</a>`;
return;
}
if(config.mode==='pending'){box.innerHTML='<h2>Agenda pendiente de configuración</h2><p>Configura GHL_CALENDAR_URL con el enlace o embed HTTPS de GoHighLevel. No se ha creado ninguna reserva.</p>';return;}
const j=await api('/api/slots');
box.innerHTML='<p class="notice">Modo de prueba local: estos horarios no reservan una llamada real ni envían correos.</p>'+(j.slots.length?`<div class="slots">${j.slots.map(slot=>`<button class="slot" data-slot="${esc(slot)}">${esc(dt.format(new Date(slot)))}<span>Horario de prueba local</span></button>`).join('')}</div>`:'<p>No quedan horarios de prueba disponibles.</p>')+'<p class="status" role="status" aria-live="polite"></p>';
let busy=false;
box.querySelectorAll('[data-slot]').forEach(b=>b.onclick=async()=>{if(busy)return;busy=true;box.querySelectorAll('button').forEach(x=>x.disabled=true);try{const result=await api('/api/bookings',{slot:b.dataset.slot});session.booking=result.booking;qualification();}catch(error){box.querySelector('.status').textContent=error.message;box.querySelectorAll('button').forEach(x=>x.disabled=false);busy=false;}});
}
function thanks(){main.classList.add('thanks-page');if(!session.booking || !session.qualification?.qualified)return location.replace('/registro');const demo=session.booking.mode==='demo',decision=session.qualification.decision;const partnerSection=decision&&decision!=='solo'?'<div class="panel"><h2>Aprovecha al máximo tu sesión</h2><p>Para aprovechar al máximo tu sesión, te recomendamos que la persona con quien tomas decisiones financieras esté presente en la reunión. Así podrán resolver todas sus dudas juntos y avanzar sin perder tiempo.</p></div>':'';main.innerHTML=`<section class="hero"><span class="success-symbol" aria-hidden="true">✦</span><p class="eyebrow">${demo?'PRUEBA COMPLETADA':'GRACIAS'}</p><h1>${demo?'Completaste el recorrido de prueba':'Gracias, recibimos tus respuestas.'}</h1></section>${bookingInfo()}<div class="panel"><h2>${demo?'Prueba local completada':'Detalles de tu sesión'}</h2><p>${demo?'Esta prueba guardó el horario y tus respuestas en el backend. No se envió un correo ni se creó una reunión en Google Meet.':'Consulta la confirmación de tu calendario para conocer los detalles de la sesión. La integración con Google Meet y el envío de correo aún no están conectados.'}</p></div>${partnerSection}`;}
function noFit(){if(!session.qualification || session.qualification.qualified)return location.replace('/registro');main.innerHTML='<section class="hero"><h1>Gracias por compartir tu perfil con nosotros</h1><p>Por ahora, creemos que Bosco no es la opción adecuada para que inviertas en este momento — y preferimos ser honestos contigo antes que hacerte perder el tiempo.</p><p>Pero eso no significa que no puedas prepararte para dar el salto cuando estés listo.</p></section><section class="section"><h2>Lo que puedes hacer hoy</h2><div class="list"><article class="item"><span class="number">01</span><div><p><strong>Sigue aprendiendo:</strong> te compartiremos recursos gratuitos sobre cómo hacer crecer tu capital y prepararte para invertir.</p></div></article><article class="item"><span class="number">02</span><div><p><strong>Construye tu capital:</strong> con estrategia y tiempo, la oportunidad correcta llegará cuando estés listo.</p></div></article><article class="item"><span class="number">03</span><div><p><strong>Mantente en contacto:</strong> cuando tu situación cambie, con gusto te acompañamos.</p></div></article></div></section><p>Mientras tanto, nos pondremos en contacto contigo para compartirte información útil sobre finanzas personales e inversión.</p>';}
function legal(kind){const privacy=kind==='privacidad';main.innerHTML=`<article class="legal"><a class="back" href="/">← Volver al proyecto</a><h1>${privacy?'Información de privacidad':'Términos de uso'}</h1>${privacy?'<p>Al completar el formulario, compartes tu nombre, email, WhatsApp y respuestas sobre tu interés de inversión para preparar y dar seguimiento a tu solicitud de información.</p><h2>Uso de los datos</h2><p>La información se registra en el sistema del sitio. Si se habilitan las integraciones, también se envía a los proveedores de agenda y gestión de contactos utilizados para atender tu solicitud. Los servicios externos que lleguen a habilitarse se rigen además por sus propios avisos de privacidad.</p><h2>Contacto y solicitudes</h2><p>Puedes solicitar información sobre el tratamiento, actualización o eliminación de tus datos a Marisol durante el seguimiento de tu solicitud.</p>':'<p>Este sitio presenta información del proyecto BOSCO Departamentos para ayudarte a preparar una sesión informativa con Marisol Caro.</p><h2>Información del proyecto</h2><p>Los precios, fechas, disponibilidad y condiciones deben confirmarse con la documentación vigente antes de realizar una operación. Las cifras de renta y plusvalía son referencias presentadas por el proyecto; los resultados individuales pueden variar.</p><h2>Testimonios</h2><p>Los testimonios describen experiencias personales. No representan una garantía de resultados para todas las personas.</p><h2>Agenda</h2><p>Una reserva corresponde a una sesión informativa de 45 minutos. No constituye la compra de un inmueble ni una obligación de inversión.</p>'}<p class="notice">Texto informativo provisional. La versión definitiva, los datos del responsable y el canal de contacto formal están pendientes de incorporación por el titular del sitio.</p></article>`;}
try{
const route=location.pathname.replace(/\/$/,'')||'/';
const preview=route==='/registro'&&new URLSearchParams(location.search).get('preview')==='1';
[config,content]=await Promise.all([preview?Promise.resolve({}):api('/api/config'),fetch('/content.json').then(r=>{if(!r.ok)throw new Error('No se pudo cargar el contenido.');return r.json();})]);
if(preview){
session={booking:null,qualification:null};
qualification(true);
}else{
try{session=await api('/api/session');}catch(error){session=null;sessionError=error.message;}
session ||= {booking:null,qualification:null};
if(['/registro','/calendar'].includes(route)){
await registration();
if(route==='/registro'){
const link=document.createElement('a');
link.className='preview-entry';
link.href='/registro?preview=1';
link.textContent='Vista previa del formulario (sin crear reservas ni enviar datos)';
document.querySelector('#calendar')?.after(link);
}
}else if(route==='/gracias')thanks();
else if(route==='/no-apto')noFit();
else if(['/privacidad','/terminos'].includes(route))legal(route.slice(1));
else await landing();
}
}catch(error){main.innerHTML=`<div class="panel"><h1>No pudimos cargar esta página</h1><p>${esc(error.message)}</p><a href="${esc(location.pathname)}">Volver a intentar</a></div>`;}
