import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,readFile,rm} from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {createApp,createHandler,slots} from '../server.mjs';
async function setup(env={}){const dir=await mkdtemp(path.join(os.tmpdir(),'bosco-'));const server=createApp({dataDir:dir,env:{PUBLIC_ORIGIN:'http://localhost:5173',NODE_ENV:'development',CALENDLY_URL:'',CALENDLY_API_TOKEN:'',CALENDLY_EVENT_TYPE_URI:'',GHL_LEAD_WEBHOOK_URL:'',...env}});await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${server.address().port}`;return {dir,base,close:async()=>{server.closeAllConnections();await new Promise(r=>server.close(r));await rm(dir,{recursive:true,force:true});}};}
const payload={name:'Persona de prueba',email:'persona@example.com',whatsapp:'+52 999 123 4567',experience:'no',goal:'family',timeline:'30days',capital:'medium',monthly:'medium',decision:'partner',consent:true};
const post=(base,route,body,cookie)=>fetch(base+route,{method:'POST',headers:{'Content-Type':'application/json',...(cookie?{Cookie:cookie}:{})},body:JSON.stringify(body)});
async function booking(a){const r=await post(a.base,'/api/bookings',{slot:slots()[0]});assert.equal(r.status,201);return r.headers.get('set-cookie').split(';')[0];}
test('landing pública y rutas, sin gate; datos privados inaccesibles',async()=>{const a=await setup();try{for(const route of ['/','/registro','/gracias','/no-apto','/privacidad','/terminos']){const r=await fetch(a.base+route);assert.equal(r.status,200);assert.match(await r.text(),/BOSCO/);}for(const route of ['/backend/data/leads.jsonl','/.env','/assets/..%5C.env'])assert.equal((await fetch(a.base+route)).status,404);}finally{await a.close();}});
test('MP4 acepta HEAD, rangos completos, sufijos y rechaza rangos inválidos',async()=>{const a=await setup();try{const url=a.base+'/assets/videos/francelia.mp4';const h=await fetch(url,{method:'HEAD'});assert.equal(h.status,200);assert.equal(h.headers.get('content-type'),'video/mp4');const r=await fetch(url,{headers:{Range:'bytes=0-99'}});assert.equal(r.status,206);assert.equal((await r.arrayBuffer()).byteLength,100);const end=await fetch(url,{headers:{Range:'bytes=-20'}});assert.equal((await end.arrayBuffer()).byteLength,20);assert.equal((await fetch(url,{headers:{Range:'bytes=999999999-'}})).status,416);assert.equal((await fetch(url,{headers:{Range:'bytes=-0'}})).status,416);}finally{await a.close();}});
test('slots solo próximas 48h y sin reserva duplicada concurrente',async()=>{const a=await setup();try{const now=Date.now();assert.ok(slots(now).every(x=>Date.parse(x)>now&&Date.parse(x)<=now+172800000));const responses=await Promise.all([post(a.base,'/api/bookings',{slot:slots()[0]}),post(a.base,'/api/bookings',{slot:slots()[0]})]);assert.deepEqual(responses.map(x=>x.status).sort(),[201,409]);assert.equal((await post(a.base,'/api/bookings',{slot:new Date(now+3*86400000).toISOString()})).status,422);}finally{await a.close();}});
test('agenda antes de preguntas; sesión, lead y condicional guardados',async()=>{const a=await setup();try{assert.equal((await post(a.base,'/api/qualification',payload)).status,409);const cookie=await booking(a);const r=await post(a.base,'/api/qualification',payload,cookie);assert.equal(r.status,201);assert.equal((await r.json()).qualified,true);const s=await fetch(a.base+'/api/session',{headers:{Cookie:cookie}}).then(x=>x.json());assert.equal(s.qualification.decision,'partner');const saved=JSON.parse((await readFile(path.join(a.dir,'leads.jsonl'),'utf8')).trim());assert.equal(saved.email,payload.email);assert.equal(saved.qualified,true);assert.ok(saved.bookingId);assert.equal((await post(a.base,'/api/qualification',payload,cookie)).status,200);assert.equal((await readFile(path.join(a.dir,'leads.jsonl'),'utf8')).trim().split('\n').length,1);}finally{await a.close();}});
for(const [key,value] of [['timeline','evaluating'],['capital','low'],['monthly','low']])test(`filtro negativo ${key} validado en servidor`,async()=>{const a=await setup();try{const cookie=await booking(a);const r=await post(a.base,'/api/qualification',{...payload,[key]:value},cookie);assert.equal(r.status,201);assert.equal((await r.json()).qualified,false);}finally{await a.close();}});
test('validación de opciones, consentimiento, formato y origen',async()=>{const a=await setup();try{const cookie=await booking(a);for(const change of [{email:'incorrecto'},{goal:'inventado'},{consent:false},{name:'<script>'}])assert.equal((await post(a.base,'/api/qualification',{...payload,...change},cookie)).status,422);const r=await fetch(a.base+'/api/qualification',{method:'POST',headers:{'Content-Type':'application/json',Origin:'https://otro.example',Cookie:cookie},body:JSON.stringify(payload)});assert.equal(r.status,403);}finally{await a.close();}});
test('producción no ofrece agenda demo ni confirmaciones falsas',async()=>{const a=await setup({NODE_ENV:'production',DEMO_BOOKING:'true'});try{const c=await fetch(a.base+'/api/config').then(r=>r.json());assert.equal(c.mode,'pending');assert.equal((await post(a.base,'/api/bookings',{slot:slots()[0]})).status,503);}finally{await a.close();}});
test('límite de envíos devuelve Retry-After sin exponer secretos',async()=>{const a=await setup({LEAD_RATE_LIMIT:'1',CALENDLY_API_TOKEN:'secreto'});try{await post(a.base,'/api/bookings',{});const r=await post(a.base,'/api/bookings',{});assert.equal(r.status,429);assert.ok(Number(r.headers.get('retry-after'))>0);assert.doesNotMatch(await fetch(a.base+'/api/config').then(r=>r.text()),/secreto/);}finally{await a.close();}});
test('Calendly real: verifica estado, tipo de evento, duración y ventana en servidor',async()=>{
 const dir=await mkdtemp(path.join(os.tmpdir(),'bosco-live-'));const eventType='https://api.calendly.com/event_types/evento-45';let scenario='valid';
 const server=createApp({dataDir:dir,env:{PUBLIC_ORIGIN:'https://bosco.example',NODE_ENV:'production',SUPABASE_URL:'https://project.supabase.co',SUPABASE_SERVICE_ROLE_KEY:'service-role-key-long-enough-for-tests',CALENDLY_URL:'https://calendly.com/marisol/sesion',CALENDLY_API_TOKEN:'token-privado',CALENDLY_EVENT_TYPE_URI:eventType},fetch:async (url,options)=>{
  if(String(url).includes('/rest/v1/rpc/'))return new Response(JSON.stringify({allowed:true,retry_after:60}),{status:200});
  if(String(url).includes('/rest/v1/'))return new Response(null,{status:201});
  if(url.includes('/invitees/'))return new Response(JSON.stringify({resource:{status:'active',event:'https://api.calendly.com/scheduled_events/evento',email:payload.email,name:payload.name}}),{status:200});
  const start=Date.now()+(scenario==='late'?3*86400000:3600000);return new Response(JSON.stringify({resource:{status:'active',event_type:scenario==='wrong-type'?'https://api.calendly.com/event_types/otro':eventType,start_time:new Date(start).toISOString(),end_time:new Date(start+(scenario==='short'?1800000:2700000)).toISOString(),location:{join_url:'https://meet.google.com/abc-defg-hij'}}}),{status:200});
 }});
 await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${server.address().port}`;
 try{const body={invitee:'https://api.calendly.com/scheduled_events/evento/invitees/persona'};for(const value of ['late','wrong-type','short']){scenario=value;assert.equal((await post(base,'/api/bookings',body)).status,422);}scenario='valid';const r=await post(base,'/api/bookings',body);assert.equal(r.status,201);assert.equal((await r.json()).booking.mode,'calendly');assert.equal((await post(base,'/api/bookings',{invitee:'https://otro.example/invitees/persona'})).status,422);}finally{server.closeAllConnections();await new Promise(r=>server.close(r));await rm(dir,{recursive:true,force:true});}
});
test('Calendly entregado aparece por defecto, sin token ni .env',async()=>{const a=await setup({CALENDLY_URL:undefined,NODE_ENV:'production'});try{const c=await fetch(a.base+'/api/config').then(r=>r.json());assert.equal(c.calendlyUrl,'https://calendly.com/rubengutierrezdv/new-meeting');assert.equal(c.mode,'calendly-embed');assert.equal((await fetch(a.base+'/api/slots')).status,409);}finally{await a.close();}});
test('referencia del widget habilita preguntas, sin inventar fechas ni confirmar en servidor',async()=>{const a=await setup({CALENDLY_URL:'https://calendly.com/rubengutierrezdv/new-meeting'});try{const event='https://api.calendly.com/scheduled_events/evento';const r=await post(a.base,'/api/bookings',{event,invitee:event+'/invitees/persona'});assert.equal(r.status,201);const b=(await r.json()).booking;assert.equal(b.verification,'browser-event-only');assert.equal(b.start,null);assert.equal(b.meetUrl,'');const cookie=r.headers.get('set-cookie').split(';')[0];assert.equal((await post(a.base,'/api/qualification',payload,cookie)).status,201);const saved=JSON.parse((await readFile(path.join(a.dir,'bookings.jsonl'),'utf8')).trim());assert.equal(saved.mode,'calendly-embed');assert.equal((await post(a.base,'/api/bookings',{event,invitee:'https://api.calendly.com/scheduled_events/otro/invitees/persona'})).status,422);}finally{await a.close();}});
test('producción requiere almacenamiento y explica el fallo sin simular guardados',async()=>{const a=await setup({NODE_ENV:'production',CALENDLY_URL:'https://calendly.com/rubengutierrezdv/new-meeting'});try{const config=await fetch(a.base+'/api/config').then(r=>r.json());assert.equal(config.storageReady,false);const session=await fetch(a.base+'/api/session');assert.equal(session.status,200);assert.equal((await session.json()).booking,null);const event='https://api.calendly.com/scheduled_events/evento';const result=await post(a.base,'/api/bookings',{event,invitee:event+'/invitees/persona'});assert.equal(result.status,503);assert.match((await result.json()).error,/No se guardaron los datos/);assert.equal((await fetch(a.base+'/api/config').then(r=>r.json())).storageReady,false);}finally{await a.close();}});
test('producción persiste reservas, respuestas y sesión solo por Supabase',async()=>{const dir=await mkdtemp(path.join(os.tmpdir(),'bosco-supabase-'));const writes=[];let storedSession;const event='https://api.calendly.com/scheduled_events/evento';const server=createApp({dataDir:dir,env:{PUBLIC_ORIGIN:'https://bosco.example',NODE_ENV:'production',SUPABASE_URL:'https://project.supabase.co',SUPABASE_SERVICE_ROLE_KEY:'service-role-key-long-enough-for-tests',CALENDLY_URL:'https://calendly.com/rubengutierrezdv/new-meeting'},fetch:async(url,options={})=>{if(String(url).includes('/rest/v1/rpc/'))return new Response(JSON.stringify({allowed:true,retry_after:60}),{status:200});if(String(url).includes('/rest/v1/sessions?')&&options.method!=='POST')return new Response(JSON.stringify(storedSession?[storedSession]:[]),{status:200});if(String(url).includes('/rest/v1/')){const body=options.body?JSON.parse(options.body):null;writes.push({url:String(url),body,headers:options.headers});if(String(url).includes('/sessions?on_conflict='))storedSession={booking:body.booking,qualification:body.qualification,expires_at:body.expires_at};return new Response(null,{status:201});}if(String(url)===event)return new Response(JSON.stringify({resource:{status:'active',event_type:'https://api.calendly.com/event_types/test',start_time:'2030-01-01T12:00:00Z',end_time:'2030-01-01T12:45:00Z'}}),{status:200});return new Response(JSON.stringify({resource:{status:'active',event,email:payload.email,name:payload.name}}),{status:200});}});await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${server.address().port}`;try{const booked=await post(base,'/api/bookings',{event,invitee:event+'/invitees/persona'});assert.equal(booked.status,201);const cookie=booked.headers.get('set-cookie').split(';')[0];const result=await post(base,'/api/qualification',payload,cookie);assert.equal(result.status,201);const session=await fetch(base+'/api/session',{headers:{Cookie:cookie}}).then(r=>r.json());assert.equal(session.qualification.qualified,true);assert.ok(writes.some(write=>write.url.includes('/bookings')));assert.ok(writes.some(write=>write.url.includes('/leads')&&write.body.data.email===payload.email));assert.ok(writes.every(write=>write.headers.apikey==='service-role-key-long-enough-for-tests'));await assert.rejects(readFile(path.join(dir,'bookings.jsonl')),{code:'ENOENT'});}finally{server.closeAllConnections();await new Promise(r=>server.close(r));await rm(dir,{recursive:true,force:true});}});
test('límite de 8 KB también se aplica al body ya parseado por Vercel',async()=>{const handler=createHandler({env:{PUBLIC_ORIGIN:'http://localhost:5173',CALENDLY_URL:''}});let status;const res={setHeader(){},writeHead(value){status=value;},end(){}};await handler({method:'POST',url:'/api/bookings',headers:{origin:'http://localhost:5173','content-type':'application/json'},body:{extra:'x'.repeat(9000)},socket:{remoteAddress:'127.0.0.1'}},res);assert.equal(status,413);});
