function section(label,title,inner){return `<section class="section"><p class="eyebrow">${esc(label)}</p><h2>${esc(title)}</h2>${inner}</section>`;}
function video(src,vsl=false,poster=''){return `<div class="media${vsl?' vsl-media':''}" data-video${vsl?' data-vsl':''}><video ${vsl?'muted autoplay':'controls'} playsinline preload="${vsl?'metadata':'none'}" ${vsl?'tabindex="0"':''} ${poster?`poster="${esc(poster)}"`:''} aria-label="${vsl?'Presentación del proyecto':'Testimonio de inversionista'}"><source src="${esc(src)}" type="video/mp4"></video>${vsl?`<div class="vsl-overlay" data-vsl-overlay hidden><button type="button" class="vsl-prompt" data-vsl-prompt aria-label="Haz clic para escuchar"><strong data-vsl-title>Tu video ya ha comenzado</strong><svg class="vsl-speaker" viewBox="0 0 64 64" aria-hidden="true" focusable="false"><path d="M8 24v16h12l16 12V12L20 24H8Z"/><path d="m46 23 12 18M58 23 46 41"/></svg><span data-vsl-message>Haz clic para escuchar</span></button><button type="button" class="vsl-resume" data-vsl-resume aria-label="Continuar video" hidden><span aria-hidden="true">▶</span><span>Continuar</span></button></div><div class="vsl-controls" aria-label="Controles del video"><button type="button" data-mute aria-label="Activar sonido" aria-pressed="false" title="Activar sonido"><span aria-hidden="true">♪</span></button><button type="button" data-full aria-label="Pantalla completa" title="Pantalla completa"><span aria-hidden="true">⛶</span></button></div>`:''}<p class="status" role="status" aria-live="polite" hidden></p></div>`;}
function mountMedia(){const compactCases=[...document.querySelectorAll('.case')].filter(article=>['Rigel','Ana Karen'].includes(article.querySelector('h3')?.textContent.trim()));if(compactCases.length===2){const group=document.createElement('div');group.className='compact-cases';const heading=document.createElement('h3');heading.className='compact-cases-heading';heading.textContent='Y muchos más inversionistas están contentos con la asesoría de Marisol';compactCases[0].before(heading,group);for(const article of compactCases){const title=article.querySelector('h3'),media=article.querySelector('.case-layout .media');article.classList.add('compact-case');article.replaceChildren(title,media);group.append(article);}}document.querySelectorAll('[data-video]').forEach(box=>{const v=box.querySelector('video');const play=box.querySelector('[data-play]'),mute=box.querySelector('[data-mute]'),seek=box.querySelector('[data-seek]');const fail=()=>{box.innerHTML='<div class="media-placeholder"><strong>Video no disponible</strong><span>Intenta nuevamente más tarde.</span></div>';};v.addEventListener('error',fail);v.querySelector('source').addEventListener('error',fail);
if(seek){const updateSeek=()=>{if(Number.isFinite(v.duration)){seek.max=String(v.duration);if(document.activeElement!==seek)seek.value=String(v.currentTime);}};v.addEventListener('loadedmetadata',updateSeek);v.addEventListener('durationchange',updateSeek);v.addEventListener('timeupdate',updateSeek);seek.oninput=()=>{if(Number.isFinite(v.duration))v.currentTime=Number(seek.value);};}
if(box.hasAttribute('data-vsl')){const overlay=box.querySelector('[data-vsl-overlay]'),prompt=box.querySelector('[data-vsl-prompt]'),resume=box.querySelector('[data-vsl-resume]'),title=box.querySelector('[data-vsl-title]'),message=box.querySelector('[data-vsl-message]'),status=box.querySelector('.status');let soundActivated=false;
const setSound=()=>{mute.setAttribute('aria-pressed',String(!v.muted));mute.setAttribute('aria-label',v.muted?'Activar sonido':'Silenciar video');mute.title=v.muted?'Activar sonido':'Silenciar video';mute.querySelector('span').textContent=v.muted?'♪':'♫';};
const showPrompt=blocked=>{overlay.hidden=false;prompt.hidden=false;resume.hidden=true;title.textContent=blocked?'Haz clic para reproducir':'Tu video ya ha comenzado';message.textContent=blocked?'Se reproducirá con sonido':'Haz clic para escuchar';prompt.setAttribute('aria-label',blocked?'Haz clic para reproducir con sonido':'Haz clic para escuchar');prompt.dataset.action=blocked?'play':'sound';};
const showResume=()=>{overlay.hidden=false;prompt.hidden=true;resume.hidden=false;};
const tryPlay=async()=>{try{await v.play();status.hidden=true;}catch{status.hidden=false;status.textContent='No se pudo reproducir el video. Intenta nuevamente.';showPrompt(true);}};
prompt.onclick=async event=>{event.stopPropagation();v.muted=false;soundActivated=true;setSound();if(prompt.dataset.action==='play'||v.paused){await tryPlay();if(!v.paused)overlay.hidden=true;}else overlay.hidden=true;};
resume.onclick=async event=>{event.stopPropagation();await tryPlay();};
mute.onclick=event=>{event.stopPropagation();v.muted=!v.muted;soundActivated=true;setSound();};
box.querySelector('[data-full]').onclick=async event=>{event.stopPropagation();try{if(box.requestFullscreen)await box.requestFullscreen();else if(v.webkitEnterFullscreen)v.webkitEnterFullscreen();else{status.hidden=false;status.textContent='La pantalla completa no está disponible en este navegador.';}}catch{status.hidden=false;status.textContent='No se pudo activar la pantalla completa.';}};
v.addEventListener('play',()=>{if(soundActivated)overlay.hidden=true;});v.addEventListener('pause',()=>{if(soundActivated&&!v.ended)showResume();});
v.addEventListener('click',event=>{if(event.target===v&&soundActivated){if(v.paused)tryPlay();else v.pause();}});
v.addEventListener('keydown',event=>{if(!soundActivated||!['Enter',' '].includes(event.key))return;event.preventDefault();if(v.paused)tryPlay();else v.pause();});
setSound();v.muted=true;v.play().then(()=>{if(v.paused)showPrompt(true);else showPrompt(false);},()=>showPrompt(true));
}else if(play){play.onclick=async()=>{try{if(v.paused){await v.play();}else v.pause();}catch{box.querySelector('.status').hidden=false;box.querySelector('.status').textContent='No se pudo reproducir el video. Intenta nuevamente.';}};v.addEventListener('play',()=>play.textContent='Pausar');v.addEventListener('pause',()=>play.textContent='Reproducir');mute.onclick=()=>{v.muted=!v.muted;mute.textContent=v.muted?'Activar sonido':'Silenciar';mute.setAttribute('aria-pressed',String(v.muted));};box.querySelector('[data-full]').onclick=async()=>{try{if(box.requestFullscreen)await box.requestFullscreen();else if(v.webkitEnterFullscreen)v.webkitEnterFullscreen();}catch{}};}
});document.querySelectorAll('img').forEach(i=>i.addEventListener('error',()=>{i.hidden=true;const p=document.createElement('p');p.className='notice';p.textContent='Imagen no disponible.';i.after(p);}));}
async function landing(){const h=esc(content.hero.title).replace('&lt;em&gt;','<em>').replace('&lt;/em&gt;','</em>');main.innerHTML=`<section class="hero"><p class="eyebrow">BOSCO · MÉRIDA, YUCATÁN</p><h1>${h}</h1><p>${esc(content.hero.subtitle)}</p><div id="vsl-slot"></div></section><div class="convert"><button class="registration-cta" type="button" data-go-form><span>Continuar al registro</span><span class="cta-arrow" aria-hidden="true">→</span></button></div><section id="registro" class="registration-section" aria-label="Registro"><div id="qualification-slot"></div></section>`+
section('CASOS REALES','Resultados de mis clientes',content.cases.map(c=>`<article class="case${c.title?' case-majo':''}"><div class="case-layout"><div class="case-copy"><h3>${esc(c.name)}</h3>${c.title?`<h4>${esc(c.title)}</h4>`:''}${c.quote?`<blockquote>“${esc(c.quote)}”</blockquote>`:''}${c.summary?`<p>${esc(c.summary)}</p>`:''}${c.metric?`<p class="metric">${esc(c.metric)}</p>`:''}</div>${c.video?video(c.video,false,c.poster):`<img class="case-photo" src="${esc(c.image)}" alt="${esc(c.name)} con Marisol" loading="lazy">`}</div></article>`).join('')+(content.pendingCase?.enabled?`<article class="case"><h3>${esc(content.pendingCase.name)} · inversionista satisfecho</h3><img class="case-photo" src="${esc(content.pendingCase.image)}" alt="${esc(content.pendingCase.name)}" loading="lazy"></article>`:''))+
section('POR QUÉ ESTE PROYECTO ES SEGURO','4 razones por las que tu inversión está protegida',trustBlocks())+
section('EL PROYECTO','Todo lo que obtienes al invertir en este proyecto',`<p>Un departamento que trabaja por ti — con acompañamiento real de inicio a fin.</p>${list(content.offer,'offer-list')}<div class="media"><img src="${esc(content.assets.project)}" alt="Avance de construcción del proyecto BOSCO" loading="lazy" width="1200" height="800"></div><div class="location-block"><p class="eyebrow">DÓNDE ESTÁ TU INVERSIÓN</p><h3>${esc(content.location.title)}</h3><p>${esc(content.location.description)}</p><div class="news">${content.news.map(n=>`<article><img class="news-image" src="${esc(n.image)}" alt="${esc(n.imageAlt)}" loading="lazy" decoding="async"><strong>${esc(n.source)}</strong><p>${esc(n.title)}</p></article>`).join('')}</div><p class="fine">${esc(content.location.delivery)} · ${esc(content.location.developer)}</p></div>`)+
section('MÁS INVERSIONISTAS CONTENTOS',content.investorsTitle,`<div class="investors">${content.assets.investors.map((src,i)=>`<img src="${esc(src)}" loading="lazy" decoding="async" width="600" height="600" alt="Inversionistas del proyecto, fotografía ${i+1}">`).join('')}</div>`);
document.querySelector('#vsl-slot').innerHTML=video(content.assets.vsl,true);mountMedia();mountMotion();mountQualification();document.querySelector('[data-go-form]').onclick=()=>{const target=document.querySelector('#registro');target.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'start'});target.querySelector('input,iframe')?.focus({preventScroll:true});};}
function trustBlocks(){return `<div class="trust-blocks">${content.trust.map(([title,text],i)=>`<article class="trust-block"><div class="trust-copy"><span class="number">${String(i+1).padStart(2,'0')}</span><h3>${esc(title)}</h3><p>${emphasis(text)}</p></div>${trustVisual(content.trustMedia[i])}</article>`).join('')}</div>`;}
function emphasis(text){let safe=esc(text);for(const phrase of ['PROFECO','15 años de experiencia','licencias de construcción','tu inversión está protegida','invertí en él','propio dinero'])safe=safe.replace(phrase,`<strong>${phrase}</strong>`);return safe;}
function trustVisual(m){if(m.kind==='projects')return `<figure class="trust-visual"><div class="project-pair">${m.images.map(src=>`<img src="${esc(src)}" loading="lazy" alt="Proyecto de CONSUR">`).join('')}</div><figcaption>${esc(m.label)}</figcaption></figure>`;if(m.kind==='photo')return `<figure class="trust-visual"><img src="${esc(m.image)}" loading="lazy" alt="Marisol junto a otras personas frente a los logos de Consur y Edifor"><figcaption>${esc(m.label)}</figcaption></figure>`;return `<figure class="trust-visual document-illustration"><div class="paper-stack ${m.kind==='permits'?'four-papers':''}" aria-hidden="true">${Array.from({length:m.kind==='permits'?4:2},()=>'<div class="paper"><span></span><i></i><i></i><i></i><i></i><i></i><b></b></div>').join('')}</div><figcaption>${esc(m.label)}</figcaption></figure>`;}
function mountMotion(){if(matchMedia('(prefers-reduced-motion: reduce)').matches||!('IntersectionObserver' in window))return;const observer=new IntersectionObserver(entries=>{entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('is-visible');observer.unobserve(e.target);}});},{threshold:.08});document.querySelectorAll('.trust-block,.case,.item,.news article').forEach(e=>{e.classList.add('reveal');observer.observe(e);});}
function list(items,variant=''){return `<div class="list ${esc(variant)}">${items.map(([title,text],i)=>`<article class="item"><span class="number">${String(i+1).padStart(2,'0')}</span><div><h3>${esc(title)}</h3><p>${esc(text)}</p></div></article>`).join('')}</div>`;}
const fields=[['experience','¿Ya has invertido en bienes raíces antes?',[['experienced','Sí, ya tengo experiencia'],['first-time','No, es mi primera vez']]],['goal','¿Qué quieres lograr con esta inversión?',[['income','Generar ingresos pasivos sin depender de mi trabajo'],['family','Construir patrimonio para mi familia'],['diversify','Diversificar lo que ya tengo invertido'],['bank','Hacer crecer mi dinero que está parado en el banco']]],['timeline','¿En cuánto tiempo quieres invertir?',[['30days','En los próximos 30 días'],['2-3months','En 2 o 3 meses'],['evaluating','Todavía lo estoy evaluando']]],['capital','¿Con cuánto capital cuentas hoy para invertir?',[['under-250k','Menos de $250,000 MXN'],['250-500k','$250,000 – $500,000 MXN'],['over-500k','Más de $500,000 MXN']]],['monthly','¿Cuánto puedes destinar mensualmente?',[['under-5k','Menos de $5,000'],['5-10k','$5,000 – $10,000'],['over-10k','Más de $10,000']]],['decision','¿La decisión de invertir depende únicamente de ti?',[['solo','Sí, decido yo solo'],['partner','No, lo decido con mi pareja o esposo(a)'],['family','No, lo decido con un socio o familiar']]]];
function noFit(){main.innerHTML='<section class="hero"><h1>Gracias por compartir tu perfil con nosotros</h1><p>Por ahora, creemos que Bosco no es la opción adecuada para que inviertas en este momento — y preferimos ser honestos contigo antes que hacerte perder el tiempo.</p><p>Pero eso no significa que no puedas prepararte para dar el salto cuando estés listo.</p></section><section class="section"><h2>Lo que puedes hacer hoy</h2><div class="list"><article class="item"><span class="number">01</span><div><p><strong>Sigue aprendiendo:</strong> te compartiremos recursos gratuitos sobre cómo hacer crecer tu capital y prepararte para invertir.</p></div></article><article class="item"><span class="number">02</span><div><p><strong>Construye tu capital:</strong> con estrategia y tiempo, la oportunidad correcta llegará cuando estés listo.</p></div></article><article class="item"><span class="number">03</span><div><p><strong>Mantente en contacto:</strong> cuando tu situación cambie, con gusto te acompañamos.</p></div></article></div></section><p>Mientras tanto, nos pondremos en contacto contigo para compartirte información útil sobre finanzas personales e inversión.</p>';}
