const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const main=document.querySelector('#main');
const header=()=>`<header class="qualification-header"><h2>¿Quieres más información sobre el proyecto? Responde estas preguntas y agenda tu sesión gratuita con Marisol.</h2><h1><span>Cuéntanos un poco</span><em>sobre ti</em></h1><p>Solo toma 1 minuto. Nos ayuda a preparar tu sesión para que sea 100% efectiva para ti.</p></header>`;
const safeUrl=value=>{try{const u=new URL(value);return u.protocol==='https:'?u.href:'';}catch{return '';}};
function mountQualification(){const slot=document.querySelector('#qualification-slot');if(!slot)return;slot.innerHTML=header();const url=safeUrl(settings.qualificationEmbedUrl);
if(url){slot.insertAdjacentHTML('beforeend',`<iframe class="ghl-native-frame" style="--form-height:${Math.max(600,Math.min(4000,Number(settings.formHeight)||1350))}px" src="${esc(url)}" title="Datos y preguntas de calificación de BOSCO" loading="lazy" referrerpolicy="strict-origin-when-cross-origin"></iframe>`);return;}
if(!settings.preview){slot.insertAdjacentHTML('beforeend','<p class="notice" role="status">El registro no está disponible en este momento. Intenta más tarde.</p>');return;}
slot.insertAdjacentHTML('beforeend',`<form id="qualification" class="panel form-grid"><p class="notice full">Vista previa: este formulario no guarda contactos, no envía mensajes y no reserva reuniones.</p><label class="full">Nombre completo<input name="name" autocomplete="name" required maxlength="100"></label><label>WhatsApp<input name="whatsapp" type="tel" autocomplete="tel" required maxlength="25" placeholder="+52…"></label><label>Correo electrónico<input name="email" type="email" autocomplete="email" required maxlength="254"></label>${fields.map(([name,label,options])=>`<label class="full">${esc(label)}<select name="${name}" required><option value="">Selecciona una opción</option>${options.map(([value,label])=>`<option value="${value}">${esc(label)}</option>`).join('')}</select></label>`).join('')}<p class="privacy-link full"><a href="${esc(settings.privacyUrl)}">Aviso de privacidad</a></p><button class="button full" type="submit">Enviar mis respuestas</button><p class="status full" role="status" aria-live="polite"></p></form><div id="calendar-slot" hidden></div>`);
const form=document.querySelector('#qualification');form.onsubmit=e=>{e.preventDefault();const data=Object.fromEntries(new FormData(form));const qualified=qualifies(data);if(!qualified){noFit();main.scrollIntoView({block:'start'});return;}const box=document.querySelector('#calendar-slot');box.hidden=false;box.innerHTML='<div class="panel"><h2>Elige tu horario</h2><p>Tu perfil pasa los filtros de esta vista previa. La agenda real se mostrará aquí cuando se conecte GoHighLevel.</p><p class="notice">No se creó ningún contacto ni ninguna reserva.</p></div>';box.scrollIntoView({behavior:'smooth'});};}
function calendar(){main.innerHTML='<section class="hero"><h1>Elige tu horario</h1></section><div id="calendar-slot"></div>';const url=safeUrl(settings.calendarEmbedUrl);document.querySelector('#calendar-slot').innerHTML=url?`<iframe class="ghl-native-frame calendar-native-frame" src="${esc(url)}" title="Agenda de Marisol" loading="lazy" referrerpolicy="strict-origin-when-cross-origin"></iframe>`:'<div class="panel"><p class="notice">Agenda pendiente de conexión a GoHighLevel. No hay horarios simulados ni reservas.</p></div>';}
function thanks(){const partner=settings.showDecisionCompanion?'<div class="panel"><h2>Aprovecha al máximo tu sesión</h2><p>Para aprovechar al máximo tu sesión, te recomendamos que la persona con quien tomas decisiones financieras esté presente en la reunión. Así podrán resolver todas sus dudas juntos y avanzar sin perder tiempo.</p></div>':'';
main.innerHTML=`<section class="hero"><span class="success-symbol" aria-hidden="true">✦</span><h1>¡Ya estás dentro! Tu sesión está confirmada.</h1></section><div class="panel"><h2>Confirmar reunión</h2><p>Revisa tu correo — te llegó la confirmación con el link de Google Meet. Agrégala a tu calendario ahora para que no se te pase.</p>${safeUrl(settings.calendarAddUrl)?`<a class="button" href="${esc(settings.calendarAddUrl)}" rel="noopener" target="_blank">Agregar a Google Calendar</a>`:''}</div>${partner}<div class="panel"><h2>Regalo sorpresa</h2><p>En un momento Marisol se comunicará contigo por WhatsApp con un regalo especial por dar este gran paso. Mantente pendiente.</p></div>`;}
function privacy(){main.innerHTML=`<article class="legal"><h1>Aviso de Privacidad</h1><p>Datos personales recopilados a través de marisolcaro.com</p><h2>1. Responsable del tratamiento de datos personales</h2><p>El responsable del tratamiento de sus datos personales es Marisol Caro de la Fuente, con RFC CAFM840912HI5, con domicilio en Av. José Vasconcelos 755, Piso 3, Interior A, Col. Del Valle, San Pedro Garza García, Nuevo León, C.P. 66220.</p><h2>2. Datos personales que recopilamos</h2><p>A través del formulario recopilamos nombre completo, número de teléfono (WhatsApp), correo electrónico y respuestas sobre experiencia, objetivos, plazo de inversión, capital disponible, capacidad mensual y participación en la decisión de inversión.</p><h2>3. Finalidad del tratamiento</h2><p>Los datos personales recopilados serán utilizados exclusivamente para: (a) contactarte y darte seguimiento sobre oportunidades de inversión inmobiliaria; (b) agendar una reunión de asesoría conforme a tu solicitud; (c) enviarte información de valor relacionada con bienes raíces. No se utilizarán para fines distintos a los aquí descritos.</p><h2>4. Transferencia de datos</h2><p>Sus datos personales no serán transferidos, vendidos ni compartidos con terceros sin su consentimiento expreso, salvo que sea requerido por autoridad competente conforme a la legislación aplicable.</p><h2>5. Derechos ARCO</h2><p>Usted tiene derecho a Acceder, Rectificar, Cancelar u Oponerse al tratamiento de sus datos personales (derechos ARCO). Para ejercer cualquiera de estos derechos, envíe su solicitud al correo electrónico: <a href="mailto:caromarisol@gmail.com">caromarisol@gmail.com</a> indicando su nombre completo y el derecho que desea ejercer. Atenderemos su solicitud en un plazo máximo de 20 días hábiles.</p><h2>6. Cambios al aviso de privacidad</h2><p>Nos reservamos el derecho de modificar este aviso de privacidad en cualquier momento. Cualquier cambio estará disponible en marisolcaro.com. El uso continuado de nuestros servicios implica la aceptación de dichas modificaciones.</p></article>`;}
async function run(){try{if(page==='landing')await landing();else if(page==='agenda')calendar();else if(page==='gracias')thanks();else if(page==='no-apto')noFit();else if(page==='privacidad')privacy();}catch(error){main.innerHTML='<div class="panel"><p role="alert">No se pudo cargar la página. Intenta nuevamente.</p></div>';console.error(error);}}
document.querySelector('.skip').onclick=e=>{e.preventDefault();main.focus();main.scrollIntoView({block:'start'});};
run();
