const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const main=document.querySelector('#main');
const header=()=>`<header class="qualification-header"><h2>¿Quieres más información sobre el proyecto?</h2><p class="qualification-instruction">Responde estas preguntas y agenda tu sesión gratuita con Marisol.</p><p class="qualification-description">Solo toma 1 minuto. Nos ayuda a preparar tu sesión para que sea 100% efectiva para ti.</p></header>`;
const safeUrl=value=>{try{const u=new URL(value);return u.protocol==='https:'?u.href:'';}catch{return '';}};
function mountQualification(){const slot=document.querySelector('#qualification-slot');if(!slot)return;slot.innerHTML=header();const url=safeUrl(settings.qualificationEmbedUrl);
if(url){slot.insertAdjacentHTML('beforeend',`<iframe class="ghl-native-frame" style="--form-height:${Math.max(600,Math.min(4000,Number(settings.formHeight)||1350))}px" src="${esc(url)}" title="Datos y preguntas de calificación de BOSCO" loading="lazy" referrerpolicy="strict-origin-when-cross-origin"></iframe>`);return;}
slot.insertAdjacentHTML('beforeend','<p class="notice" role="status">Agenda no disponible</p>');}
function calendar(){const url=safeUrl(settings.calendarEmbedUrl);main.innerHTML=url?`<section class="hero"><h1>Elige tu horario</h1></section><div id="calendar-slot"><iframe class="ghl-native-frame calendar-native-frame" src="${esc(url)}" title="Agenda de Marisol" loading="lazy" referrerpolicy="strict-origin-when-cross-origin"></iframe></div>`:'<section class="hero"><h1>Agenda no disponible</h1></section>';}
function thanks(){main.innerHTML='<p class="notice" role="status">Agenda no disponible</p>';}
function privacy(){main.innerHTML=`<article class="legal"><h1>Aviso de Privacidad</h1><p>Datos personales recopilados a través de marisolcaro.com</p><h2>1. Responsable del tratamiento de datos personales</h2><p>El responsable del tratamiento de sus datos personales es Marisol Caro de la Fuente, con RFC CAFM840912HI5, con domicilio en Av. José Vasconcelos 755, Piso 3, Interior A, Col. Del Valle, San Pedro Garza García, Nuevo León, C.P. 66220.</p><h2>2. Datos personales que recopilamos</h2><p>A través del formulario recopilamos nombre completo, número de teléfono (WhatsApp), correo electrónico y respuestas sobre experiencia, objetivos, plazo de inversión, capital disponible, capacidad mensual y participación en la decisión de inversión.</p><h2>3. Finalidad del tratamiento</h2><p>Los datos personales recopilados serán utilizados exclusivamente para: (a) contactarte y darte seguimiento sobre oportunidades de inversión inmobiliaria; (b) agendar una reunión de asesoría conforme a tu solicitud; (c) enviarte información de valor relacionada con bienes raíces. No se utilizarán para fines distintos a los aquí descritos.</p><h2>4. Transferencia de datos</h2><p>Sus datos personales no serán transferidos, vendidos ni compartidos con terceros sin su consentimiento expreso, salvo que sea requerido por autoridad competente conforme a la legislación aplicable.</p><h2>5. Derechos ARCO</h2><p>Usted tiene derecho a Acceder, Rectificar, Cancelar u Oponerse al tratamiento de sus datos personales (derechos ARCO). Para ejercer cualquiera de estos derechos, envíe su solicitud al correo electrónico: <a href="mailto:caromarisol@gmail.com">caromarisol@gmail.com</a> indicando su nombre completo y el derecho que desea ejercer. Atenderemos su solicitud en un plazo máximo de 20 días hábiles.</p><h2>6. Cambios al aviso de privacidad</h2><p>Nos reservamos el derecho de modificar este aviso de privacidad en cualquier momento. Cualquier cambio estará disponible en marisolcaro.com. El uso continuado de nuestros servicios implica la aceptación de dichas modificaciones.</p></article>`;}
let userNavigationStarted=false;
let initialLandingPositionApplied=false;
if(page==='landing'){const markNavigationStarted=()=>{userNavigationStarted=true;};for(const type of ['pointerdown','touchstart','wheel','keydown'])window.addEventListener(type,markNavigationStarted,{capture:true,passive:type!=='keydown',once:true});}
function positionInitialLanding(){if(initialLandingPositionApplied)return;initialLandingPositionApplied=true;const navigation=performance.getEntriesByType('navigation')[0];if(userNavigationStarted||location.hash||navigation?.type==='back_forward'||window.scrollY!==0)return;main.scrollIntoView({block:'start',behavior:'instant'});}
async function run(){try{if(page==='landing'){await landing();positionInitialLanding();}else if(page==='agenda')calendar();else if(page==='gracias')thanks();else if(page==='no-apto')noFit();else if(page==='privacidad')privacy();}catch(error){main.innerHTML='<div class="panel"><p role="alert">No se pudo cargar la página. Intenta nuevamente.</p></div>';console.error(error);}}
document.querySelector('.skip').onclick=e=>{e.preventDefault();main.focus();main.scrollIntoView({block:'start'});};
run();
